### ISSUE TITLE
Drawer has missing aria tags

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#115]
the drawer component has missing tags
![image](https://user-images.githubusercontent.com/28805105/27915257-9fb3a752-625d-11e7-9fe3-f12aaeb0c909.png)
![image](https://user-images.githubusercontent.com/28805105/27916196-433ca228-6260-11e7-9127-2e9457e00d77.png)

adding components into a drawer that already have assigned roles causes the issue
this component needs be able to accept a role as a parameter or figure out what it should be based on the role in its children

**Comment by davidjacob93** [comment]
Issue resolved.
