### ISSUE TITLE
Raised Button - Should have discernible text

### ISSUE THREAD

**Issue by davidjacob93** [manchesergit/material-ui#127]
Maybe adding a non-empty aria-label may fix the problem.

![capture](https://user-images.githubusercontent.com/25061353/28074938-dbdd1aae-6651-11e7-92c8-fc6301c37a09.PNG)

![capture1](https://user-images.githubusercontent.com/25061353/28074980-f516004e-6651-11e7-8313-bb39be66a867.PNG)

https://dequeuniversity.com/rules/axe/2.3/button-name?application=AxeChrome

**Comment by djbuckley** [comment]
this is because the buttons this issue is valid for are icon buttons that have no text associated with them
probably the best thing to do here would be to add a property for icon description and give it a default of "Button with icon", then put that out as the hidden label for the button
