### ISSUE TITLE
Dialog keyboard navigation is not reliable using shift tab

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#132]
navigating backwards with shift + tab does not reliably capture focus
the best example is the modal dialog

**Comment by davidjacob93** [comment]
@djbuckley I just checked and there is same issue with timepicker and datepicker

**Comment by djbuckley** [comment]
@davidjacob93 thats because its an issue on the dialog as far as i know and they use the dialog as their base component

**Comment by djbuckley** [comment]
you cannot tab past the first item or past the last
the tabbing isn't cyclic though, so you can't tab from the last item to the first
