### ISSUE TITLE
Test Checkbox has ID's

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#157]
Tests need to be added to prove that a CheckBox
- [ ] produces a unique ID for itself if none is given
- [ ] uses the ID given in the properties

**Comment by mak66** [comment]
Invalid issue since CheckBox has not been augmented to do anything with ids other than the default propagation of "other" properties . The enhancedSwitch, common internal component which underpins CheckBox does use or generate ids so I believe that the unit tests should be on that component.
