### ISSUE TITLE
Test the RadioButton has an ID

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#161]
Tests need to be added to prove that a RadioButton
- [ ] produces a unique ID for itself if none is given
- [ ] uses the ID given in the properties

**Comment by mak66** [comment]
Invalid issue since RadioButton has not been augmented to do anything with ids other than the default propagation of "other" properties . The enhancedSwitch, common internal component which underpins RadioButton does use or generate ids so I believe that the unit tests should be on that component.
