### ISSUE TITLE
Test the Toggle has an ID

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#162]
Tests need to be added to prove that a Toggle
- [ ] produces a unique ID for itself if none is given
- [ ] uses the ID given in the properties

**Comment by mak66** [comment]
Invalid issue since Toggle has not been augmented to do anything with ids other than the default propagation of "other" properties . The enhancedSwitch, common internal component which underpins Toggle does use or generate ids so I believe that the unit tests should be on that component.
