### ISSUE TITLE
Test Popover can be dismissed with escape

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#182]
Popover should be able to be dismissed using the escape key

**Comment by marksarnold** [comment]
Am I correct in assuming that "Phase two" is material-ui-next.com?

**Comment by djbuckley** [comment]
No, phase two is a fork of the main material-ui repo with the w3c accessibility features added.
We used the main branch for some projects but it's not very usable if you need keyboard only navigation or have to use voice over (or similar).
This fork is just about done in regards of meeting the standards.  We have been working on enhancing the test suite, so we can then return to performance updates to our original changes.

We have steered clear of the next/beta branch from the original repo as it's not currently feature comparable.
