### ISSUE TITLE
Test the first cell of a Table has content

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#199]
the first cell of a table should contain some content
this may be covered by accessibility tests

old : 
![image](https://user-images.githubusercontent.com/28805105/28424564-da459638-6d65-11e7-804e-be17922797f8.png)

new :
![image](https://user-images.githubusercontent.com/28805105/28424231-004ea5b4-6d65-11e7-89d4-3d220fd4ddbf.png)

**Comment by mak66** [comment]
Not doing this as the correct solution is to not have text but to render the select all check box in a td.
See issue #231 for resolution.
