### ISSUE TITLE
RadioButton add group role tag

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#21]
Add a role to the RadioButtonGroup.
https://dequeuniversity.com/rules/axe/2.1/radiogroup
* ###### Size 1

**Comment by woody9944** [comment]
An issue has been raised with callemall to add the functionality to enable this feature.

https://github.com/callemall/material-ui/issues/7263

**Comment by woody9944** [comment]
Awaiting change from call-me-all  to allow this fix.

**Comment by woody9944** [comment]
![lifesize-star-wars-han-solo-frozen-in-carbonite-walldoor-decal-4](https://user-images.githubusercontent.com/17280234/27949540-edba49f4-62f5-11e7-8569-c497ee6e412d.jpg)

Graphical representation.

**Comment by djbuckley** [comment]
![](http://www.jeditemplearchives.com/galleries/2011/Review_HanCarboniteTSC/Review_HanCarboniteTSC_stillA.jpg)

**Comment by djbuckley** [comment]
and going with the theme... 

![](http://www.theforce.net/swtc/Pix/diagram/ds/dsblow.gif)

looks like in fixing other things, this has been dealt with

**Comment by woody9944** [comment]
This issue has been fixed in the v1-beta version of material-ui. (Not that its much use to us)

https://github.com/callemall/material-ui/issues/7263

via 

https://github.com/callemall/material-ui/pull/7742
