### ISSUE TITLE
Tests for TextField have been written to match the results not the requirements

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#234]
The test for checking the TextField produces an ID, checks that the value has -div on the end.
Issue #203 says 

> produces a unique ID for itself if none is given

the test however checks 
```javascript
      const id = '12345';
      const expectedId = `${id}-div`;
      const wrapper = shallowWithContext(
        <TextField id={id} />
      );
      assert.strictEqual(wrapper.prop('id'), expectedId, 'should use provided id');
```
the test should not have -div on it
if the component does not pass the test, then a new issue should be raised for the failure

**Comment by davidjacob93** [comment]
Tests have been changed with new issue been added #236 for the failed unit test.
