### ISSUE TITLE
StepLabel tests have been written to the output of the control not the requirements

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#235]
The tests for StepLabel check that the id has -labelRootSpan on the end of it instead of what was specified in #194 
the test should check that the StepLabel
> produces a unique ID for itself if none is given

the test however checks
```javascript
        const id = '12345';
        const expectedId = `${id}-labelRootSpan`;
        const wrapper = shallowWithContext(
          <StepLabel id={id} />
        );
        assert.strictEqual(wrapper.prop('id'), expectedId, 'should use provided id');
```
the test should not have -labelRootSpan on it
if the component does not pass the test, then a new issue should be raised for the failure

**Comment by davidjacob93** [comment]
An issue #222 was already raised for this issue @djbuckley
