### ISSUE TITLE
Snackbar increase default timeout

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#24]
Increase the default timeout of the display when a button is visible on the bar (unless a specific value for the timeout is provided in autoHideDuration).
* ###### Size 2

**Comment by m4ttb13** [comment]
Added a bit of logic that says if autoHide < 10000 ms, set it to 10000 ms (10 seconds) - effectively adding a minimum. Would perhaps be worth looking into if its possible to detect screenreader usage - so to only increase timer if user is using a screen reader.
