### ISSUE TITLE
Snackbar add keyboard functions when theres a button

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#25]
## Keyboard
Add the button on the snackbar to the next place in the tab index, if a button is shown.
* ###### Size 8

**Comment by m4ttb13** [comment]
Focus moves to the action button when tabbed to it - discussion to be had to determine if it should auto focus onto this button or leave as it is.

**Comment by m4ttb13** [comment]
Going to sign off as it is because it is accessible, and the nature of the snackbar itself means it is not designed with accessibility in mind

**Comment by m4ttb13** [comment]
https://github.com/callemall/material-ui/issues/4116 details as far as I got. setting focus seems to move the visual but not actual focus onto the snackbar. Could not move past this.
