### ISSUE TITLE
TextField set correct role

### ISSUE THREAD

**Issue by djbuckley** [manchesergit/material-ui#33]
Child elements should use the correct role as set down in their parent components.
* ###### Size 2

**Comment by davidjacob93** [comment]
fixed with issue with some minor changed on the TextFieldLabel script. Added a variable with the roleLabel that had a string 'textbox' inside. In the label for the role assigned that variable.

**Comment by woody9944** [comment]
Fixed with f280c442cd8a95bdc24196b4bc0a6266cf5f48cf
